START:
	MOV DPTR,#41H		;数表首地址
	MOV R1,#00H		;计数清0
	MOV R2,#00H
TESTEND:
	MOVX	A,@DPTR		;取数
	INC	DPTR		;修改指针
	CJNE	A,#-1,NEXT1	;是否为数表结尾（A≠-1跳） 
	SJMP	DONE		;循环结束
NEXT1:
	CJNEA,#64H,NEXT2		;比较（A≠100跳）
	INC	R1		;100分+1
	SJMP	TESTEND
NEXT2:
	SUBB	A,#3CH		;是否小于60分
	JNC	NEXT3
	SJMP	TESTEND
NEXT3:
	INC	R2		;不及格+1
	SJMP	TESTEND
DONE:
	SJMP	DONE
